In [1]:
import numpy as np

In [12]:
import random

In [6]:
alph = np.arange(0, 10)

In [13]:
h_len = 20 
H = "".join([str(x) for x in np.random.randint(0, 10, 20)])

In [14]:
H

'79207465948431423943'

In [27]:
set(H)

{'0', '1', '2', '3', '4', '5', '6', '7', '8', '9'}

In [18]:
N1 = "920"
N2 = "484"

In [15]:
"9" in "920"

True

In [38]:
n=[]
for x in set(H):
    for i, y in enumerate((N1, N2)):
        for j, k in enumerate(y):
            if x==k:
                n.append((str(x), i,j))

In [39]:
n

[('9', 0, 0), ('0', 0, 2), ('4', 1, 0), ('4', 1, 2), ('2', 0, 1), ('8', 1, 1)]

In [30]:
R = np.zeros((2, len(H)))

In [36]:
R[0]=3
R[1] = 3

In [37]:
R

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3.]])

In [40]:
for i, x in enumerate(H):
    for k in n:
        if x==k[0]:
            R[k[1],i-k[2]]-=1
    

In [42]:
print(R)

[[3. 0. 3. 3. 3. 3. 3. 3. 2. 3. 3. 3. 3. 3. 2. 3. 3. 2. 3. 3.]
 [3. 3. 3. 2. 3. 2. 3. 2. 3. 0. 3. 2. 2. 3. 2. 3. 2. 3. 2. 3.]]
